stages:
  - setup
  - test
  - teardown
  - deploy

image: jaktestowac/python-chromedriver:3.6-xvfb

before_script:
  - cat /etc/os-release
  - google-chrome --version
  - chromedriver --version
  - pip install -r requirements.txt

setup all:
  stage: setup
#  when:  manual
  script:
    - python hello.py

test ui titles:
  stage: test
  script:
    - python -m unittest shop_sample_tests
    - python -m platform

# Manual job - NON-BLOCKING execution
test ui gdpr:
  stage: test
  when: manual
  script:
    - python -m unittest shop_gdpr_tests

# Job blocking pipeline execution: when: manual, allow_failure: false
#test ui gdpr:
#  stage: test
#  when: manual
#  allow_failure: false
#  script:
#    - python -m unittest shop_gdpr_tests


teardown end of tests:
  stage: teardown
  script:
    - python bye.py

teardown test report:
  stage: teardown
  script:
    - python generate_report.py

deploy to production:
  stage: deploy
  when: manual
  script:
    - python deploy.py