stages:
 - test

image: jaktestowac/python-chromedriver:3.6-xvfb

before_script:
  - cat /etc/os-release
  - google-chrome --version
  - chromedriver --version
  - pip install -r requirements.txt

job_test ui:
  stage: test
  script:
    - python -m unittest shop_sample_tests
    - python -m platform


