stages:
  - setup
  - test
  - teardown
  - deploy


image: ruby:2.5


before_script:
  - cat /etc/os-release
  - echo 'Global before_script'

setup all:
  stage: setup
#  when:  manual
  script:
    - python -m platform
    - python hello.py

.testTemplate:
  image: jaktestowac/python-chromedriver:3.6-xvfb
  before_script:
    - echo 'Job before_script (template now)'
    - cat /etc/os-release
    - google-chrome --version
    - chromedriver --version
    - pip install -r requirements.txt

test ui titles:
  stage: test
  extends: .testTemplate
  script:
    - python -m unittest shop_sample_tests
  artifacts:
    when: always
    paths:
      - ./testResults/

  except:
    - master

# Manual job - NON-BLOCKING execution
test ui gdpr:
  stage: test
  extends: .testTemplate
  script:
    - python -m unittest shop_gdpr_tests

  only:
    - master

  retry:
    max: 2
    when: script_failure
#UPDATE
teardown end of tests:
  stage: teardown
  script:
    - python bye.py

teardown test report:
  stage: teardown
  script:
    - python generate_report.py

deploy to production:
  stage: deploy
  when: manual
  script:
    - python deploy.py