stages:
  - setup
  - test
  - teardown

image: jaktestowac/python-chromedriver:3.6-xvfb

before_script:
  - cat /etc/os-release
  - google-chrome --version
  - chromedriver --version
  - pip install -r requirements.txt

setup all:
  stage: setup
  script:
    - python hello.py

job_test ui:
  stage: test
  script:
    - python -m unittest shop_sample_tests
    - python -m platform


teardown end of tests:
  stage: teardown
  script:
    - python bye.py

teardown test report:
  stage: teardown
  script:
    - python generate_report.py